apiVersion: v1
kind: Service
metadata:
  name: todo
spec:
  ports:
  - port: 8080
  selector:
    app: todo
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - image: 127.0.0.1:30500/todo
        name: todo
        envFrom:
        - secretRef:
            name: mysqlsecret
        env:
          # Use secret in real usage
        - name: RDS_HOSTNAME 
          value: mysql
        - name: RDS_PORT
          value: "3306"
        - name: RDS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: DB_NAME
        - name: RDS_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: DB_USERNAME
        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: DB_PASS
        - name: RDS_OPTIONS
          value: useSSL=false&allowPublicKeyRetrieval=true
        - name: AUTH
          value: "false"
        ports:
        - containerPort: 8080
          name: todo
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      initContainers:
      - name: waitforit
        image: toschneck/wait-for-it
        command: ["./wait-for-it.sh", "mysql:3306"]
         
     